spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/wanted
    username: sa
    password:

  jpa:
    show-sql: true # SQL 쿼리를 콘솔에 출력할지 여부
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # 데이터베이스 스키마 자동 생성 / 관리 기능
